- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/project.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/main-setup.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.routing.ts
File Changes:
Home Controller.cs - added action
Startup.cs - added routes
Setup.html
setup.compoment.ts
setup.routing.ts
setup.module.ts
project.json
main-setup.ts
> Created new angular app to perform basic setup page

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Account/Login.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/BasicSetup/BasicSetup.cs
Added ApplicationClasses folder in domain-model project with two files. Login.cs and BasicSetup.cs
> Added application classes folder heirarchy

- Trappist/src/Promact.Trappist.Web/Views/Shared/_BeforeLoginLayout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
_BeforeLoginLayout.cshtml : Updated to have dynamic year in the footer
questions-dashboard.html : Updated the router links for single answer & multiple answers
questions-multiple-answers.component.ts : Added
questions-multiple-answers.html : Added
questions-single-answer.component.ts : Added
questions-single-answer.html : Added
questions.module.ts : Included components for single answer & multiple answers
questions.routing.ts : Included components for single answer & multiple answers and their routing
style.scss : Updated to include styles for single answer & multiple answers
> Designed Single Answer page & Multiple Answers page.

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Category/Category.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionsRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170310075319_Initialcategorymodel.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170310075319_Initialcategorymodel.cs
- Trappist/src/Promact.Trappist.Web/Migrations/TrappistDbContextModelSnapshot.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
> Initial commit

- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_BeforeLoginLayout.cshtml
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
Redmine tasks done :
#20836 & #20837
Files changed are :
Setup.cshtml : Changed to remove material css
_BeforeLoginLayout.cshtml : Changed to remove unused class logo-area
questions-multiple-answers.html : Changed the title from Single to Multiple
setup.html : Changed to include the html for Basic Setup design
setup.module.ts : Changed to include angular2-wizard
style.scss : Changed to include the styles for Basic Setup design
systemjs.config.js : Changed to include angular2-wizard
package.json : Changed to include angular2-wizard
> Designed Basic Setup page.

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Enum/DifficultyLevel.cs
- Trappist/src/Promact.Trappist.DomainModel/Enum/ProgramingLanguage.cs
- Trappist/src/Promact.Trappist.DomainModel/Enum/QuestionType.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/CodeSnippetQuestion.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/CodingLanguage.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/QuestionBase.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/QuestionLanguageMapping.cs
- Trappist/src/Promact.Trappist.DomainModel/Seed/SeedDatabase.cs
- Trappist/src/Promact.Trappist.Web/Migrations/TrappistDbContextModelSnapshot.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
Task# 20889: Create model for code snippet question
Files added:
CodeSnippetQuestion.cs
CodingLanguage.cs
QuestionLanguageMapping.cs
SeedDatabase.cs
ProgramingLanguage.cs
File modified:
TrappistDbContext.cs - Added DbSet
DifficultyLevel.cs - Moved to DomailModel/Enum folder
QuestionBase.cs - Removed unnecessary using namespace
QuestionType.cs - Moved to DomailModel/Enum folder
Startup.cs - Added seed extension method
> Created model and support class for code snippet question

- Trappist/src/Promact.Trappist.Core/ActionFilters/GlobalExceptionFilter.cs
File Added
- GlobalExceptionFilter.cs
> gloabl exception filter added

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Core/project.json
- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Test/Test.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.module.ts
Files changed:
StartUp.cs: registered ITestsRepository
TrappistDbContext.cs: Test Model
Models: Added new folder named Test and created a new model in that named Test(task: 20858)
Repository: Created a new repository folder named Tests in that added ITestsRepository and TestsRepository (task: 20859 and 28867)
> Create test api and Model done

- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Redmine Task Done :
#21024
profile-dashboard.html, profile-edit.html, questions-dashboard.html, questions-multiple-answers.html, questions-single-answer.html, tests-dashboard.html : Changed to add container class
app.html : Changed to remove container class
test-settings.html : Added the html for test settings design
test-settings.component.ts : Added to create test settings component
test-launch-dialog.html : Added the html for test launch dialog
tests.module.ts : Changed to include test settings component
tests.routing.ts : Changed to include test settings component
style.scss : Changed to includes styles for test settings design
> Designed test settings page.

- Trappist/src/Promact.Trappist.Web/Startup.cs
- deploy.sh
Redmine Task: 20902 
File changes: Startup.cs
> Single multiple question api

- Trappist/src/Promact.Trappist.Core/Controllers/AccountController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Account/Login.cs
- Trappist/src/Promact.Trappist.Repository/Account/AccountRepository.cs
- Trappist/src/Promact.Trappist.Repository/Account/IAccountRepository.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
files changed are:
AccountController.cs
AccountRepository.cs
Issues solved:
Tasks #21060-Creating login model
Tasks #20933-Validation of input fields for login
Tasks #20934-verify the inputs with the database record and on successful login redirect to test dashboard
> All login features are updated

- Trappist/src/Promact.Trappist.Core/Controllers/TestDashBoardController .cs
- Trappist/src/Promact.Trappist.Repository/TestDashboard/ITestDashBoardRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestDashboard/TestDashBoardRepository .cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-dashboard.pipe.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
**Files Added:**
TestDashBoardController
ITestDashBoardRepository
TestdashBoardRepository
test-dashboard,pipe
tests.model.ts
tests.service.ts
**Files Changed:**
Startup.cs
tests-dashboard.component.ts
test.module.ts
tests-dashboard.html
> Test DashBoard Features

- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Redmine Tasks Done :
#20848 & #21025
Redmine Task Partially Done :
#21026
profile-edit.html : Changed to add class half-width and also added routing for cancel button
delete-category-dialog.html : Added the html for delete category dialog design
questions-dashboard.component.ts : Changed to include delete category dialog
questions-dashboard.html : Changed to include delete category dialog and routing to Programming
questions-multiple-answers.html : Changed class name
questions-single-answer.html : Changed class name
questions-programming.component.ts : Added questions-programming component
questions-programming.html : Added html for questions-programming design
questions.module.ts : Changed to include delete category dialog component & questions-programming component …
> Designed Questions-Programming Page.

- .travis.yml
- Trappist/src/Promact.Trappist.Test/BasicSetup/BasicSetupRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/BootstrapFixure.cs
- Trappist/src/Promact.Trappist.Test/Category/CategoryRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/ClearDatabase.cs
- Trappist/src/Promact.Trappist.Test/Promact.Trappist.Test.xproj
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/project.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Added Test Repositories for
Questions
Category
Test
TestConduct
Report
BasicSetup
Added Bootstrap.cs - registering dependencies
Added BootstrapFixture.cs - to initialize collectionfixture
Added ClearDatabaseAndSeed - to clear data of each test
Updated .travis.yml - build and run test
> Unit testing bootstrap with xUnit and Collection Fixtures

- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
Files Changed:
Startup.cs (Removed Json Serialization portion)
tests.model.ts (Typscript format changed to camelCase)
> Typscript Format changed to camelCase

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/CodeSnippetQuestionDto.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRespository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/project.json
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/project.json
Task# 21028: Creation of API to post code snippet question
File Added:
CodeSnippetQuestionDto.cs
Files Modified:
QuestionController.cs
IQuestionRepository.cs
QuestionRepository.cs
Startup.cs
project.json - Added automapper in dependency
> Added API to handle post request to add new code snippet question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-question-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-question-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
change-password-dialog.component.ts : Added to separate the dialog component
profile-dashboard.component.ts : Changed to separate the dialog component
profile.module.ts : Changed to separate the dialog component
add-category-dialog.component.ts : Added to separate the dialog component
delete-category-dialog-component.ts : Added to separate the dialog component
delete-question-dialog.component.ts : Added to include delete question dialog component
delete-question-dialog.html : Added to include delete question dialog design
questions-dashboard.component.ts : Changed to separate the dialog component & include delete question dialog component
questions-dashboard.html : Changed to include delete question dialog
questions.module.ts : Changed to separate the dialog component …
> Designed Snackbar & seperated all dialog components.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
setup.component.ts : Changed to include wizard step events
setup.html : Changed to include actions area
style.scss : Changed to include styles for actions area of setup wizard
> Changed the actions area of the setup wizard.

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/QuestionFetching/SingleMultipleAnswerQuestionApplicationClass.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/CodeSnippetQuestion.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/Question.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/SingleMultipleAnswerQuestion.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
#21219
SingleMultipleAnswerQuestionApplicationClass.cs - changed base class to Question.cs
CodeSnippetQuestion.cs - changed base class to BaseModel.cs and added foreign key from Question.cs
Question.cs - Renamed from QuestionBase.cs to Question.cs
SingleMultipleAnswerQuestion.cs - Added foreign key from Question.cs
QuestionRepository.cs - Added To-Do comment 
**Checks**
> Updated question model

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
#21219
TrappistDbContext.cs - Added Question into DbSet
**Checks**
> Added Question DbSet

- .gitignore
- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/gulpfile.js
changed relative paths for production, updated gitignore to exclude dist folder
> added dist folder for publishing in Web.csproj files

- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Redmine Task Done :
#21021
test-sections.component.ts : Added to include test sections component
test-sections.html : Added to include test sections selection page design
tests.module.ts : Changed to include test sections component
tests.routing.ts : Changed to include test sections component
style.scss : Changed to include styles for test sections selection page design & also included styles for validation messages.
> Designed test sections selection page.

- .travis.yml
- Trappist/src/Promact.Trappist.Web/gulpfile.js
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/tslint.json
> Integrated tslint

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
NA
TrappistDbContext.cs - added sync method for save changes
Bootstrap.cs - added context lifetime
**Checks**
> solved issue of context lifetime from test project. added async method for save changes

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/QuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/SingleMultipleAnswerQuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/SingleMultipleQuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/Question.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRespository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
#21264
QuestionController.cs- Create new common api
QuestionAC.cs- Create new application class
Question.cs- Added cretedby and updatedby field
SingleMultipleQuestion.cs- Changed name to singleMultipleQuestionAC.cs
QuestionRepository.cs -Added await and async
IQuestionRepository.cs -Added await and async 
**Checks**
> Create common api for single/multiple and code snippet question

- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-question-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-answer/questions-single-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
#21022, #21023
change-password-dialog.html - Changed to replace i tags with em tags
profile-dashboard.html - Changed to replace i tags with em tags
add-category-dialog.html - Changed to replace i tags with em tags
delete-category-dialog.html - Changed to replace i tags with em tags
delete-question-dialog.html - Changed to replace i tags with em tags
questions-dashboard.html - Changed to replace i tags with em tags
questions-multiple-answers.html - Changed to replace i tags with em tags
questions-programming.html - Changed to replace i tags with em tags
questions-single-answer.html - Changed to replace i tags with em tags
test-sections.html - Changed to replace i tags with em tags
test-launch-dialog.html - Changed to replace i tags with em tags …
> Deigned test-questions-selection page. Fixed Sonarqube issues.

- Trappist/src/Promact.Trappist.Core/Controllers/AccountController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Repository/BasicSetup/BasicSetupRepository.cs
- Trappist/src/Promact.Trappist.Web/setup.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#21150, #21151
test-questions.component.ts - Changed double quotes to single quotes
test-sections.component.ts - Changed double quotes to single quotes
test-view.component.ts - Added to include test view component
test-view.html - Added to include test view design
tests.module.ts - Changed to include test view component
tests.routing.ts - Changed to include test view component
style.scss - Changed to include styles for test view page
**Checks**
> Designed Test View page.

- Trappist/src/Promact.Trappist.DomainModel/Models/Question/Question.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
Fixed removal of codes from Question.cs
question.cs
**Checks**
- issue 1
- issue 2
**Comments**
> Question.cs file updated

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/CodeSnippetQuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/QuestionAC.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRespository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
#21028
CodeSnippetQuestionAC.cs - Renamed CodeSnippetQuestionDto to CodeSnippetQuestionAC
QuestionAC.cs - Changed CodeSnippetQuestion to CodeSnippetQuestionAC
IQuestionRepository.cs - Changed return type of function AddCodeSnippetQuestion to Task
QuestionRepository.cs - Updated function AddCodeSnippetQuestion according to new model
Startup.cs - Added configuration to ignore self referencing loop
**Checks**
-no known issue
**Comments**
No work done at client side so "client side code comments" is unchecked.
> Updated code snippet question post API

- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/setup.json
#21028
QuestionRepository.cs - Renamed QuestionId to Id
**Checks**
-no known issue
**Comments**
No work done at client side so "client side code comments" is unchecked.
> Fixed issue with QuestionId

- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Login.cshtml - Changed to include general-error-msg class
setup.html - Changed to include proper validations
style.scss - Changed to include styles for proper validations & loader
**Checks**
> Made after development design changes.

- Trappist/src/Promact.Trappist.Web/setup.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
**Fixed rebasing Issue**
questions-dashboard.html
**Checks**
- issue 1
- issue 2
**Comments**
> fixed issue of rebasing

- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/core.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/http.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-multiple-answers/questions-multiple-answers.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
**Checks**
- issue 1
- issue 2
**Comments**
> lint error solved

- Trappist/src/Promact.Trappist.Core/Controllers/ProfileController.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/ApplicationUser.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/ChangePasswordModel.cs
- Trappist/src/Promact.Trappist.Repository/Profile/IProfileRepository.cs
- Trappist/src/Promact.Trappist.Repository/Profile/ProfileRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Profile/ProfileRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/setup.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/password.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.service.ts
#20860, #20862, #20865, #20866,#21274
ProfileControllrer.cs-Added To create methods for get and update profile details, update password & logout
IProfileRepository.cs-Added To create methods for get and update profile details, update password
ProfileRepository.cs-Added To create methods for get and update profile details, update password
ChangePasswordModel.cs- Added View Model to update new password of the user in the database model
ProfileRepositoryTest.cs-Added for unit testing but unit testing is not done
HomeController.cs-Changed to add authorization
profile-dashboard.component.ts-Changed to display details of the user's profile in the profile page
profile-edit.component.ts-Changed to let user edit his profile and save the changes …
> Profile Management & Change Password

- Trappist/src/Promact.Trappist.Core/Controllers/ProfileController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
#20865, #20866
change-password-dialog.component.ts-corrected validations
change-password-dialog.html- corrected validations
ProfileControllrer.cs-Added object to return function of UpdateProfile
**Checks**
-  [x] Unused variables, methods, blank spaces and name spaces. 
**Comments**
> Validations corrected for change password

- Trappist/src/Promact.Trappist.Core/Controllers/AccountController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Account/ForgotPassword.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Account/Login.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Account/ResetPassword.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/ChangePasswordModel.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Views/Account/ForgotPassword.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/ResetPassword.cshtml
- Trappist/src/Promact.Trappist.Web/setup.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
Validation & Spelling correction 
AccountController.cs - Changed else part in resetpassword method and corrected spelling issues
IStringConstants.cs-Added InvalidTokenError property and corrected spelling issues
StringConstants.cs-Added InvalidTokenError property definition and corrected spelling issues
Login.cstml-Removed required attribute & autocomplete attribute and changed error messages
ResetPassword.cshtml-Removed required attribute and changed error message
ForgotPassword.cshtml-Removed required attribute
setup.json-Changed database name to "trappist" in connectionstring
Login.cs-Corrected error message for password field
ResetPassword.cs-Added confirm password required field& added regular expression to validation password field …
> Login validation feature

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRespository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
**Fixed Issue**
Edited the comments of
* GetAllQuestions API of questions controller
* GetAllQuestionsAsync method of QuestionRepository
* getAllQuestions method of questions-dashboard.component
* getAllQuestions method of questions-service.ts
QuestionController.cs
QuestionRepository.cs
question-dashboard.component.ts
questions-services.ts
**Checks**
N/A
**Comments**
Only the comments of few methods are updated in this pull request.
> Updating comments

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
- Trappist/src/Promact.Trappist.Repository/Categories/ICategoryRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/categories.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
Edited Comments.
CategoryController.cs
CategoryRepository.cs
ICategoryRepository.cs
categories.service.ts
questions-dashboard.component.ts
questions.service.ts
**Checks**
N/A
**Comments**
In all cases 'q' of Questions and 'c' of Categories are updated to Upper-Case
> updated the comments

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#21155, #21157
instructions.html - Changed to include test conduct instructions design
style.scss - Changed to include styles for test conduct instructions design
**Checks**
> Designed test conduct instructions page.

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Category/Category.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
- Trappist/src/Promact.Trappist.Repository/Categories/ICategoryRepository.cs
- Trappist/src/Promact.Trappist.Test/Category/CategoryRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/categories.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/category.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/rename-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/rename-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
Fixed Issues
#20907,#20910
Design Rename- dialog-component
Files Changed
CategoryController.cs:Method Added CheckDuplicateCategoryNameAsync()
Category.cs: Maxlength Changed to 150
CategoryRepository.cs:Method Added CheckDuplicateCategoryNameAsync() and and method name changed
ICategoryRepository.cs : Method Added CheckDuplicateCategoryNameAsync() and method name changed
CategoryRepositoryTest.cs:Method Name Updated, Add unit test for GetCategoryById and CheckDuplicateCategoryName
categories.service.ts:addCategory updateCategory Method Added
StringConstants.cs:Added CategoryNameExistsError
IStringConstants.cs:Added CategoryNameExistsError
add-category-dialog.html : Added Data binding and bind button with function
questions-dashboard.component.ts : Rename- dialog-component added …
> Category Management Client Side Api

- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Profile/ProfileRepositoryTest.cs
#21274
ProfileRepositoryTest.cs-Added unit testing for ProfileRepository
Bootstrap.cs- Added dependency
**Checks**
N/A
**Comments**
N/A
> Profile Management unit testing

- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/ClearDatabase.cs
Resolved unit testing issue 
Bootstrap.cs - Added GlobalUtil in AddScope
ClearDatabase.cs - Added dbContext.Database.EnsureDeleted();
**Checks**
- No issue
**Comments**
NA
> Fixed issues with unit testing

- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
#21439
QuestionsRepositoryTest.cs - Renamed property name to latest name in CreateCodingQuestion function
**Checks**
- AddCodeSnippetQuestionAsync test will fail due to change in application class
**Comments**
NA
> Renamed properties name according to the latest change

- Trappist/src/Promact.Trappist.Test/Category/CategoryRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
* Unit testing for GetAllCategoriesAsync() is implemented 
CategoryRepositoryTest.cs - Reason for change/add
**Checks**
N/A
**Comments**
Unit testing for fetching all categories from the database is implemented.
> Get all category unit testing

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
Question-dashboard-componene.ts : added  properties 
**Checks**
**Comments**
> Fixed issue in question-dashboad.component file

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#21436, #21437
instructions.html - Changed to include the button type as button
test-end.component.ts - Added to include test end component
test-end.html - Added to include test end design
test-summary.component.ts - Added to include test summary component
test-summary.html - Added to include test summary design
conduct.module.ts - Changed to include these new components
conduct.routing.ts - Changed to include these new components
tests-dashboard.html - Changed to include title attribute on test name
style.scss - Changed to include styles for these new designs
**Checks**
> Designed Test Summary page & End Test Message page.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
questions-dashboard.html - Changed to include title attribute for category name
questions-single-multiple-answer.html - Changed to include missing classes 
style.scss - Changed to include some design changes 
**Checks**
> Made after development design changes for questions module.

- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#20867, #20869
test-create-dialog.html - Changes for validation message display
tests-dashboard.component.ts - rectified condition checking for null test
**Checks**
> New test Creation Issue Fixed

- Trappist/src/Promact.Trappist.Web/package.json
Fixed ng2-ckeditor issue
package.json - Added ng2-ckeditor
**Checks**
- Not known 
**Comments**
NA
> Added ng2-ckeditor

- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#**Fixed Issues**
#21192
Bootstrap.cs - Add mapper initialization
QuestionRepositoryTest.cs - Add test method for AddSingleMultipleAnswerQuestion
Startup.cs - Remove extra mapper initialization
questions-single-multiple-answer.html - Solve click button event issue
questions-single-multiple-answer.component.ts - Add method to add option
QuestionRepository.cs -Add application user
IQuestionRepository.cs - Add application user
**Checks**
N/A
**Comments**
> Unit testing of single multiple answer question

- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
* implemeted unit testing for GetAllQuestionAsync method
QuestionRepositoryTest.cs
**Checks**
N/A
**Comments**
unit testing for fetching all questions from the database is implemented.
> implemented GetAllQuestions unittesting

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
Fixed issue of maximum option and created by
QuestionController.cs - Add application user
QuestionRepositoryTest.cs - Create application user
questions-single-multiple-answer.component - Fixed maximum option creation issue
question-single-multiple-answer.html - Fixed maximum option creation issue
**Checks**
N-A
**Comments**
> Fixed issue of maximum number of option creation

- Trappist/src/Promact.Trappist.Repository/BasicSetup/BasicSetupRepository.cs
- Trappist/src/Promact.Trappist.Utility/DbUtil/DbUtility.cs
Migration issue while setup
DBUtility.cs - added condition to delete database on each migration as of now
BasicRepository.cs - added exception message to know the issue
**Checks**
- [x ] Naming Conventions
**Comments**
> solved migration issue at first time setup

- Trappist/src/Promact.Trappist.Web/Views/Shared/_BeforeLoginLayout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
_BeforeLoginLayout.cshtml - Changed to include css bundles
questions-programming.html - Changed to include some after development design changes
questions-single-multiple-answer.html - Changed to include some after development design changes
setup.html - Changed to include some after development design changes
test-settings.html - Changed to include some after development design changes
style.scss - Changed to include some after development design changes 
**Checks**
> Made some design changes.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/shared/test-conduct-footer/test-conduct-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/shared/test-conduct-footer/test-conduct-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/shared/test-conduct-header/test-conduct-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/shared/test-conduct-header/test-conduct-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
instructions.html - Changed to include test conduct header & footer tags
register.html - Changed to include test conduct header & footer tags
test-conduct-footer.component.ts - Added to create test conduct footer component
test-conduct-footer.html - Added to include test conduct footer markup
test-conduct-header.component.ts - Added to create test conduct header component
test-conduct-header.html - Added to include test conduct header markup
test-end.html - Changed to include test conduct header & footer tags
test-summary.html - Changed to include test conduct header & footer tags
conduct.html - Changed to remove test conduct header & footer markup
conduct.module.ts - Changed to include test conduct header & footer components
create-test-footer.component.ts - Added to …
> Made structural changes for create test module and test conduct module.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
#21508
profile-dashboard.html - Made proper spacing after each label tag
**Checks**
> Fixed bug #21508

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#21514
questions-dashboard.html - Changed to remove unwanted classes
style.scss - Changed to include styles like applying display table & table-cell on questions dashboard module to resolve this bug
**Checks**
> Fixed bug #21514

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
#21483
QuestionController.cs - Add update question method
IQuestionRepository.cs - Add method for edit single multiple answer question
QuestionRepository.cs - Remove unnecessary comment and add method
**Checks**
N-A
**Comments**
> Create server side api for edit single multiple answer question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#21534,#21536
questions-single-multiple-answer.component.ts - Add method to check option is selected or not
questions-single-multiple-answer.html - Call component method
**Checks**
N-A
**Comments**
> Fixed multiple answer question related issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/question-display.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#21531
* question-display.ts - to fix the display regarding bug
* questions-dashboard.component.ts
**Checks**
N/A
**Comments**
The bug that was there regarding question display has been resolved.
> bug regarding question display failure is fixed.

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Test/Test.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestAttendees.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170411061243_TestConductModel.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170411061243_TestConductModel.cs
#21161
TestConductServiceResponse.cs-Added response class for handling response of server side API.
TrappistDbContext.cs-Added TestAttendees tabel.
test.cs-Added relationship between Test and TestAttendees model class.
TestAttendees.cs-Added model class for test attendees.
**Checks**
N/A
**Comments**
N/A
> Added test conduct registration model

- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
#21507
profile-edit.html- Added maximum length for organization name
**Checks**
N/A
**Comments**
N/A
> Fixed bug #21507

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#21473
test.component.ts - Added to include conduct test component
test.html - Added to include conduct test view design
conduct.module.ts - Changed to include conduct test component
conduct.routing.ts - Changed to include conduct test component
style.scss - Changed to include styles for conduct test view design
**Checks**
> Designed preview & launched test view.

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/Question.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
#21451 #21452 #21453 #21454 #21455 #21456
* question-dashboard.component.ts 
* question-dashboard.html
**Checks**
N/A
**Comments**
Filtering and Searching feature is implemented
> implemented filtering of Questions feature

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/CodeSnippetQuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/QuestionDetailAC.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
#21519
QuestionRepository.cs - Fixed incorrect question language mapping
**Checks**
- No Issues
**Comments**
NA
> Fixed issue with question language mapping

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
* Counting issue fixed
question-dashboard.component.ts
**Checks**
**Comments**
Counting issue is fixed.
> break is given at the end of switch statements

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
N-A
CategoryController.cs : Method name changed. Added suffix in Controller Action. 
CategoryController
**Checks**
**Comments**
> Added suffix in controller Action Name

- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
#21549
Login.cshtml - Removed onpaste attribute
**Checks**
N/A
**Comments**
N/A
> fixed issue related to password for login

- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile.service.ts
Issue related to edit profile
profile-edit.component.ts - Removed parameter from updateUserDetails(), Changed editUserDetails() to getUserDetails()
profile.service.ts-Removed editUserDetails()
**Checks**
N/A
**Comments**
N/A
> Resolved issue related to edit profile

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.component.ts
#21553
**add-category-dialog.component.ts** : Added trim property
**rename-category-dialog.component.ts** : Added trim property 
**Checks**
**Comments**
leading and trailing spaces issue
> leading and trailing issue solved

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
#21532
question-dashboard.component.ts - Removed getCategoryById() method.
**Checks**
- [] Server side code comments (proper English, grammar and no spelling mistakes)
N/A
**Comments**
N/A
> fixed categoryName undefined bug

- Trappist/src/Promact.Trappist.Utility/ExtensionMethods/StringExtensions.cs
Added extension to remove unwanted white spaces.
StringExtensions.cs - to add AllTrinm() extension method on string.
**Checks**
**Comments**
> alltrim extension to remove unwanted white spaces from string.

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
#21191, #21193, #21195
* TestController.cs - Added server side delete test code
* ITestRepository.cs - Added server side delete test code
* TestRepository.cs - Added server side delete test code
* delete-test-dialog.component.ts - Added client side delete test code
* delete-test-dialog.html - Added delete validation dialog
* tests.service.ts - Added delete test API call
* test-dashboard.component.ts - Added DeleteTestDialogComponent's component Instance
* test-dashboard.html - Passed test object as parameter in deleteTest
* TestsRepositoryTest.cs -  Added unit testing for delete test code
**Checks**
N/A
**Comments**
> delete test feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
#28867
test-create-dialog.html - used ngModelChange
**Checks**
> fixed the validation message display issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
individual-report.component.ts - Added component for individual report
individual-report.html - Added initial html page for individual report
test-report.component.ts - Added component for test report
test-report.html - Added to include design for test report
reports.component.ts - Added component for reports
reports.html - Added to include designs for reports
reports.module.ts - Added reports module
reports.routing.ts - Added reports routing
shared.module.ts - Changed to include MD2-Datatable
test-questions.html - Changed to include only-checkbox class
test-view.html - Changed header-block class to test-create-header
app.module.ts - Changed to include reports module
style.scss - Changed to include styles for test report design
**Checks**
> Designed View Test Report page.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
test-report.html - Removed unused ngmodel from search input
**Checks**
> Removed unused ngmodel from test-report page.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
Fixed issue #236 of github
questions.module.ts - removed ckeditor & formModule import
app.module.ts - removed ckeditor & formModule import
shared.module.ts - added ckeditor import
questions-programming-component.ts - removed formModule import
**Checks**
- No issue
**Comments**
NA
> Moved ckeditor & formModule to shared module

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
CategoryController.cs : Added Extension method to trim whitespaces.
**Checks**
**Comments**
> trailing and leading issue fixed

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#21595
delete-test-dialog.component.ts - Removed isTestAttendeeExist() function
test-dashboard.component.ts - added isTestAttendeeExist() call to server
delete-test-dialog.html - removed loader
**Checks**
N/A
**Comments**
N/A
> fixed bug #21595 

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
#21599
TestController.cs - Added authorize attribute
**Checks**
N/A
**Comments**
N/A
> Fixed bug #21599

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#21159
tests-dashboard.component.ts- replaced push() with unshift().
**Checks**
> resolved bug for display of newly created test on test dashboard

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.component.ts
#20859
test-create-dialog.component.ts- removed unrequired parameter from method
**Checks**
> resolved parameter passing issue in add test method 

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/CodeSnippetQuestionAC.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
#21476
QuestionController.cs - Added controller method to update Question
IQuestionRepository.cs - Added function definition of UpdateCodeSnippetQuestionAsync
QuestionRepository.cs - Added implementation of function UpdateCodeSnippetQuestionAsync
**Checks**
- No issue known
**Comments**
NA
> Implemeted API to update code snippet question

- Trappist/src/Promact.Trappist.Web/Views/Account/ForgotPassword.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/ForgotPasswordConfirmation.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/ResetPassword.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Account/ResetPasswordConfirmation.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
ForgotPassword.cshtml - Changed to replace h1 tag with h2 tag
ForgotPasswordConfirmation.cshtml - Changed to replace h1 tag with h2 tag
Login.cshtml - Changed to replace h1 tag with h2 tag
ResetPassword.cshtml - Changed to replace h1 tag with h2 tag
ResetPasswordConfirmation.cshtml - Changed to replace h1 tag with h2 tag
Conduct.cshtml - Changed to replace h1 tag with p tag and some classes
Index.cshtml - Changed to replace h1 tag with p tag and some classes
Setup.cshtml - Changed to replace h1 tag with p tag and some classes
profile-dashboard.html - Changed to include class mb20
profile-edit.html - Changed to include class mb20
questions-dashboard.html - Changed to include class mb20 & some changes in search input
questions-single-multiple-answer.html - Changed to …
> Made design improvements related to fonts and spacing.

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
Fixed issue #266 
CategoryController.cs : Region Added and Removed AllTrim() method from AddCategoryAsync() and UpdateCategoryAsync().
CategoryRepository.cs:Region Added and Add Alltrim() Method to AddCategoryAsync(),UpdateCategoryAsync() and IsCategoryExistAsync().
**Checks**
**Comments**
> Region added in Controller and Repository.

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
Github issue #265 
QuestionRepository.cs - Added regions
QuestionController.cs - Added regions
**Checks**
- No known issue
**Comments**
NA
> Added code region for private method, public method and constuctors

- README.md
- Trappist/src/Promact.Trappist.Test/Promact.Trappist.Test.csproj
- appveyor.yml
> Code coverage integration

- appveyor.yml
> updated yml to fix indentation issue

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/QuestionDetailAC.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
Added Id in QuestionDetailAC application class
QuestionDetailAC.cs - Added Id property
QuestionRepositoryTest.cs - Modified unit testing for update code snippet question
**Checks**
- No Issue
**Comments**
NA
> Added Id in QuestionDetailAC class, updated unit testing

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.component.ts
add-category-dialog.component.ts:Added trim() method before if condition
update-category-dialog.component.ts:Added trim() method before if condition
**Checks**
**Comments**
N-A
> Resolved bug Related to Category Add and Update

- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/code-snippet-questions-test-cases.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/enum-test-case-type.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
#21591 #21592
* questions-programming.component.ts
* questions-programming.html
**Checks**
**Comments**
> Remove test cases

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
Error message class is rectified
question-programming.html
**Checks**
**Comments**
> rectified error class mistake

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Test/TestCategory.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Test/TestQuestion.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170419114708_Test-Question-Selection.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170419114708_Test-Question-Selection.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
#21171
TestCategory.cs - Added Model for TestCategory
TestQuestion.cs- Added Model for TestQuestion
**Checks**
**Comments**
NA
> Test category question model

- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
startup.cs - Changed to include conduct routing changes made by Roshni
test-settings.html - Changed to include small-width class
style.scss - Changed to make small-width & half-width classes independent of form-control
**Checks**
> Fixed design issue related to validation msg on settings page.

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/BasicSetup/BasicSetupRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.model.ts
#21162, #21163,#21493
TestConductController.cs-Added this controller for register test attendees method. 
TestConductRepository.cs-Added this class for register test attendee methods implementation.
ITestConductRepository.cs-Added interface for decleration of  TestConductRepository.cs methods.
Bootstrap.cs-Added mocking of Globalutil and added service of TestConductRepository.
TestConductRepositoryTest.cs-Added unit test cases for registration functionality.
Startup.cs-Added service of TestConductRepository.
conduct.module.ts-Added provider ConductService.
conduct.service.ts-Added a method for accessing HTTP service.
register.component.ts-Added a method for getting test attendee detail.
register.html-Added validation of registration fields. …
> Added Test conduct registration functionality

- Trappist/src/Promact.Trappist.Core/Controllers/CategoryController.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
- Trappist/src/Promact.Trappist.Repository/Categories/ICategoryRepository.cs
- Trappist/src/Promact.Trappist.Test/Category/CategoryRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/categories.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#21517, #21518
CategoryController.cs - called IsCheckCategoryInQuestionsById() method
ICategoryRepository.cs - declared IsCheckCategoryInQuestionsById() method
CategoryRepository.cs - implementations of IsCheckCategoryInQuestionsById() method
delete-category-dialog-component.ts - display appropriate message
**Checks**
-[x] Naming Conventions
-[x] Server side code comments (proper English, grammar and no spelling mistakes)
-[x]Client side code comments (proper English, grammar and no spelling mistakes)
-[x] Unused variables, methods, blank spaces and name spaces.
-[x] Optimal Code and code formatting
-[x] Commit History is proper, no merge is done.
-[x] Commit/pull request messages should be proper to justify your feature
-[x] All test cases are executed …
> Add validation on remove category.

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-question-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-question-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
#21464
#21465
#21466
1.**QuestionController.cs** : Added API DeleteQuestion() for delete question
2.**IQuestionRepository.cs** : Added Method GetQuestionByIdAsync()and DeleteQuestionAsync() and IsQuestionExistInTestAsync()
3.**QuestionRepository.cs** :  Added Method GetQuestionByIdAsync() and DeleteQuestionAsync(),IsQuestionExistInTestAsync()
4.**.QuestionsRepositoryTest.cs** : Added method DeleteQuestionTest() and GetQuestionByIdTest for unit-test
5.**delete-question-dialog.component.ts** : Added Component and methods for delete Question
6.**delete-question-dialog.html** : deleteQuestion() Added
7.**questions.service.ts** : Added Client side API deleteQuestion() for delete Question
8.**questions-dashboard.component.ts** : changes in …
> delete question functionality implemented

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
register.html - Changed to remove h4 class from labels
test.html - Changed to add a few more question numbers
test-summary.html - Changed to replace mb40 class with mb30
change-password-dialog.html - Changed to remove h4 class from labels
profile-dashboard.html - Changed to replace h5 class with font-semibold
profile-edit.html - Changed to remove h4 class from labels
add-category-dialog.html - Changed to remove h4 class from label
update-category-dialog.html - Changed to remove h4 class from label
questions-programming.html - Changed to remove h4 class from labels
individual-report.html - Changed to include test-name class
test-report.html - Changed to include test-name & mt5 class
setup.html - Changed to remove h4 class from labels
test-launch-dialog.html - Changed to …
> Design improvements related to font size & spacing.

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
**questions-dashboard.component.ts** : Added splice method to delete question from dashboard
**questions-dashboard.html** :added question object
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/297)
> Fixed issue related to delete question

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/CodeSnippetQuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Question/CodeSnippetQuestion.cs
- Trappist/src/Promact.Trappist.Repository/Questions/IQuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170421041209_UpdatedCodeSnippetQuestionModel.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170421041209_UpdatedCodeSnippetQuestionModel.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/code.snippet.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/enum-test-case-type.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
#21477 #21478
QuestionController.cs - Added controller function GetQuestionByIdAsync
CodeSnippetQuestionAC.cs - Removed using TestCase Application class
CodeSnippetQuestion.cs - Modified model class, inherited base model
IQuestionRepository.cs - Added definition of method GetQuestionByIdAsync
QuestionRepository.cs - Added implementation of GetQuestionByIdAsync, updated implementation of UpdateCodeSnippetQuestionAsync
Bootstrap.cs - Added automapper configuration
QuestionsRepositoryTest.cs - Added test for GetQuestionByIdAsync and modified test for UpdateCodeSnippetQuestionAsync
Startup.cs - Added automapper configuration
code.snippet.model.ts - Renamed member to support auto mapping
enum-test-case-type.ts - Renamed enum value for display purpose …
> Code snippet client side implementation of edit functionality

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
HomeController.cs - Changed to add view for Page Not Found
PageNotFound.cshtml - Added to include Page Not Found design
style.scss - Changed to remove min-width from test-name on create test header
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/298)
> Designed Page Not Found error message page.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#21818
**questions-dashboard.component.ts**: added countQuestion() method to count and question deleted from question Array
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/302)
> Bug solved (#21818)

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#21822
questions-single-multiple-answer.component.ts - optimize code and remove unnecessary variable
questions-single-multiple-answer.html - Remove extra line 
**Checks**
N-A
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/303)
> Solve Bug #21822

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#21814
**delete-category-dialog.component.ts** : Added MdDialogRef 
**questions-dashboard.component.ts** : changed deleteCategoryDialog() method
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/305)
> Bug Fixed #21814

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/single-multiple-answer-question-option.model.ts
21545,21729
**questions-dashboard.component.ts** : added method duplicateQuestion()
**questions-dashboard.html**: method added in button click.
**questions-programming.component.ts** : implemented duplicate Question feature for code snippet question.
**questions-single-multiple-answer.component.ts**: implemented duplicate Question feature for single-multiple answer question.
**questions-single-multiple-answer.html**:changes some validation
**questions.routing.ts** :added route for duplicate question
**single-multiple-answer-question-option.model.ts** : added id property in option model
**Checks**
**Comments**
--- …
> duplicate question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#21826
questions-single-multiple-answer.component.ts - Add variable initialization
questions-single-multiple-answer.html - Add required field
**Checks**
N-A
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/307)
> Solved bug #21826

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/delete-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#21829
**delete-category-dialog.component.ts** : Added category object instead of Category Class
**questions-dashboard/questions-dashboard.component.ts** : category deleted from CategoryArray.
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/306)
> Fixed issue #21829

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
#21144
tests-question.component.ts - added loader
TestRepository.cs-modified condition for checking test question
create-test-footer.html- corrected the route
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/309)
> changes for correct routes

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
#21844
test-create-dialog.html - added keyup.enter and tabindex
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/312)
> changes for 'Tab' and 'Enter' click

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
#21821
test-launch-dialog.component.ts-Added code for changing the test link format
test-launch-dialog.html-Binded the variable containing the correct format of test link
create-test-header.component.ts-Taken testNameReference as input
create-test-header.html-changed the required validation of test name
test-sections.component.ts-Stored the test name coming from the server side in testNameReference variable
test-sections.html-Passed the testNameReference variable to the create-test-header component
test-questions.component.ts-Stored the test name coming from the server side in testNameReference variable
test-questions.html-Passed the testNameReference variable to the create-test-header component
**Checks**
---
This change is [<img …
> Solved required error message issue

- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
#21598
ITestConductRepository.cs - Added missing slash
TestConductRepository.Test.cs-Added test cases for test instruction 
instructions.html-Added function on button click
instructions.component.ts-Added navigation to question details page
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/313)
> unit testing of test instruction 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
#21836
questions-programming.component.ts - Removed 'Please Select by Category' option from default
questions-programming.html - Added value attribute set to empty
**Checks**
- No
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/314)
> Solved bug in validating default option for category drop down while adding code snippet question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
#21858
**questions-dashboard.component.ts** : Added property "loader"
**questions-dashboard.html** : Added class "loader-container" and "spinner" class
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/315)
> Implemented loader when page redirects to question page

- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_BeforeLoginLayout.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
PageNotFound.cshtml - Changed to remove favicon link tag
_BeforeLoginLayout.cshtml - Changed to remove favicon link tag
_Layout.cshtml - Changed to remove favicon link tag
style.scss - Changed to include styles for starred effect in reports grid & focus effect of buttons
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/317)
> Designed starred effect & focus effect of buttons. Removed favicon link tags.

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#21855
TestController.cs - Changed return values for isTestAttendeeExists() function
test-dashboard.component.ts-Changed to check if the test can be deleted or not
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/316)
> Resolved bug 21855

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
**questions-dashboard.component.ts** : changes in getAllQuestions() and categoryWiseFilter() method.
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/318)
> display a loader when category wise filtering performed

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
#21879
questions-programming.html.cs - Removed touch validation from code selection
**Checks**
- No Issue
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/322)
> Fixed issue where error message is being shown after clicking on a language and before language chip is added.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
message added in test-questions.component
#21173
test-dashboard.component.ts: Modified (loader added)
tests-questions.component.ts : Modified (loader added and if no test found user will be redirected to 
test-dashboard)
tests.questions.html: Modified (Message added if no category present in a test)
systemjs.config.js: Modified (Removed comma because it was giving a warning)
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/319)
> Loader added to test-dashboard

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.html
#21862
**add-category-dialog.html** : Added validation
**update-category-dialog.html** : Added validation
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/321)
> Fixed issue related to category "Create" and "Update" button 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#21867
**questions-single-multiple-answer.html** : Validation changed
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/325)
> Fixed issue Edit Single/Multiple answer Question-Correct Answers are selectable without adding answer value

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/duplicate-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/duplicate-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
#21199, #21200, #21201
TestController.cs - added server side duplicate test code
ITestRepository.cs - added server side duplicate test code
TestRepository.cs - added server side duplicate test code
TestRepositoryTest.cs - added unit testing for DuplicateTest() function
duplicate-test-dialog.component.ts - added client side duplicate test code
test.service.ts - added client side duplicate test code
test-dashboard.component.ts - added client side duplicate test code
test-dashboard.html - added duplicateTest() link
duplicate-test-dialog.html - added to display duplicate test dialog
**Checks**
N/A
**Comments**
N/A
--- …
> Duplicate test feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.html
#21862
**add-category-dialog.html** : added (keyup.enter) method
**update-category-dialog.html** :  added (keyup.enter) method
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/326)
> clicking on enter button will save category name

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/328)
> coverall's issue updated

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
#21898
test-dashboard.component.ts=added editTest and isTestAttendeeExist functions
test-dashboard.html - changed i tag to em tag and a tag to button.
test.moddel.ts - added isEditTestEnable variable of boolean type
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/329)
> Edit test feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#21905
**questions-single-multiple-answer.html**: change placeholder
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/333)
> Fixed issue Place holder text- for Single and multi choice question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
#21902
create-test-header.component.ts - Modified code for editing test name 
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/331)
> Solved bug related to edit test name

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
#21904, #21878 #21868 #21866
* question-programming.component.ts
* question-programming.html
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/330)
> Bug test cases

- Trappist/src/Promact.Trappist.DomainModel/Models/Test/Test.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
#21908
Login.cshtml - added asp-route-returnurl to store the value of ReturnUrl from route
TestRepositoryTest.cs- added few lines to cover the left part of the code
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/335)
> changes for ReturnUrl and unit testing

- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
#21874
profile-edit.component.ts - added loader variable
profile.edit.html- added loader
change-password-dialog.component.ts-added loader variable
change-password-dialog.html- added loader
TestRepositoryTest.cs-changed variable newtest to newTest
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/336)
> Fixed bug #21874

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
#21902
create-test-header.html - Solved the issue related to edit test name.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/339)
> Bug fixed #21902

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.html
#21996
**add-category-dialog.component.ts** : added variable isButtonClicked
**add-category-dialog.html** : disabled create button
**update-category-dialog.component.ts** : added variable isButtonClicked
**update-category-dialog.html** : disabled update button
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/343)
> Fixed issue Category created with same name.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
#21941
profile-edit.html -Changed pattern and error message for contact no
register.html-Changed input pattern for contact no
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/345)
> Fixed bug #21941

- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
* Smooth scrolling to top of the page on selection of category
* system.config.js
* shared.module.ts
* question-dashboard.component.ts
* question-dashboard.html
* app.html
* package.json
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/348)
> implemented smooth scroll

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Test/CategoryAC.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/category.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
#21359, #21929
test-question.component.ts: Modified
test-question.html: total number of questions field displayed
TestRepository.cs: Modified GetAllQuestionsByIdAsync(), GetTestByIdAsync() userId condition is added while fetching questions.
TestController.cs : Modified GetAllQuestionsByIdAsync(), GetTestByIdAsync() userId condition is added while fetching questions.
CategoryAc.cs: Modified QuestionCount field is added
TestRepositoryTest.cs:  Modified
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/347)
> Test question selection

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
**Fixed Issues
#21995
test-create-dialog.component.ts - made isSelectButton true or false accordingly at appropriate places
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/350)
> changes for better handling of multiple clicks

- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
smooth scrolling removed
* question-programming.component.ts
* question-programming.html
* app.html
* shared.module.ts
* package.json
* system.config.js
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/351)
> smooth scrolling undone.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
#21962
shared.module.ts - Added MD2TooltipModule for implementing tooltip functionality
test-launch-dialog.component.ts-Added code for displaying tooltip message and selecting the test link on clicking the content_copy icon.
test-launch-dialog.html-Binded tooltip message to content_copy icon and added methods for changing tooltip message and selecting the test link.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/349)
> Added tooltip functionality 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/update-category-dialog.html
#22000
**add-category-dialog.component.ts** : added onEnter() method
**update-category-dialog.component.ts** : added onEnter() method
**add-category-dialog.html** 
update-category-dialog.html
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/352)
> Fixed issue Category create and update 

- Trappist/src/Promact.Trappist.DomainModel/Models/Test/Test.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170504092833_Added properties to Test.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170504092833_Added properties to Test.cs
Added properties to the Test model 
Test.cs - added IsPaused and IsLaunched to the Test model for Launch, Pause and resume of test
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/355)
> added properties to Test model

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/TestConduct/TestInstructionsAC.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/testInstructions.model.ts
#21981
TestInstructionsAC.cs - Added property browsertolerance of enum type
testInstructions.model.ts-Added property browsertolerance of enum type
TestCondutcRepository.cs-Changed browsertolerance type to enum
TestCondutcRepositoryTest.cs-Changed brosertolerance type inside private method
testInstructions.html-removed "in no perticular order" and bind browsertolerance properly
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/356)
> fixed bug #21981

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
Display test details over test dashboard.
test-question.html: Modified ,"/" removed "out of" added
test-dashboard.html: Modified , displayed rest details of test
test-dashboard.component.ts : Modified getAllTest() method loader added properly
test.model.ts: numberOfTestSections,numberOfTestQuestions field added.
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/359)
> numberofTestQuestions,numberOfTestSections field added to test.model.ts,

- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
Unit Testing Coverage
TestRepositoryTest.cs: Modified
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/360)
> Unit testing covered all codes

- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
Covered the left part of code in server side unit testing
TestRepositoryTest.cs - added the left part of code
**Checks**
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/361)
> covered all paths of code in unit testing

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/category.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#22029, #22021
TestController.cs - Added restriction to selection of sections and questions on existence of test attendees for a particular test.
category.model.ts-Added a boolean variable to check the existence of questions in a particular category.
create-test-header.component.ts-Added code for preventing multiple clicks on updating test name.
test-questions.component.ts-Added code for disbaling the selection of questions on existence of test attendees for a test.
test-questions.html-Added message to notify the user that an on-going test cannot be edited and disabled the selection and deselection of checkboxes for selecting and deselecting questions on existence of test attendees for that test.
test-sectons.component.ts-Added code for disabling the …
> Implemented edit test functionality

- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/test-link-popover/test-link-popover.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/test-link-popover/test-link-popover.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
shared.module.ts - Changed to remove Md2TooltipModule reference
create-test-header.component.ts - Changed to declare showTestLink boolean variable
create-test-header.html - Changed to include test link button & its popover
test-link-popover.component.ts - Added to include test link popover component
test-link-popover.html - Added to include the html for test link popover
test-questions.html - Changed to include only-checkbox class
test-launch-dialog.html - Changed to replace tooltip with mdTooltip
test-view.component.ts - Changed to declare showTestLink boolean variable
test-view.html - Changed to include test link popover
tests.module.ts - Changed to include test link popover component reference
style.scss - Changed to include disabled menu item style, test link popover …
> Created test link popover component.

- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
**QuestionsRepositoryTest.cs** : added IsQuestionExistInTest() method and IsQuestionExistInTest() and IsQuestionExistInTestTest() method
and 
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/362)
> Covered question repository unit test

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
#22043
TestConductRepository.cs-Changed feature to check category names which contain only question 
TestConductRepositoryTest.cs-Added etst case for not valid testlink instructions details
instruction.component.ts-Added checking for not negative sign
instruction.html-Binded sign in html
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/365)
> Modified test instructions feature

- Trappist/src/Promact.Trappist.Utility/EmailServices/EmailService.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
Removed the proceed further without email setting feature
EmailService.cs- updated client authentication mechanism
setup.component.ts- Deleted function for poceedfurtherwithoutemailsetting method
setup.html- Deleted necessary tag from html
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/370)
>  Removed proceed further without emailsetting feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
#22080
test-questions.html - Fixed visibility of message
test-sections.html - Fixed visibility of message
**Checks**
- No issue
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/372)
> Fixed visibility of message in the background while loading

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
#22028
test-view.component.ts-Added code for getting the selected questions only from the question list.
test-view.html-Removed div containing the condition for displaying the selected questions.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/373)
> Fixed bug #22028

- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/http.service.ts
#22035, #22036
http.service.ts- lines added to prevent caching for IE
**Checks**
- issue 1
- issue 2
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/369)
> Prevent request caching for internet explorer.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/incomplete-test-creation-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
questions-dashboard.component.ts - Changed to fix create & update category bug, done by Asif.
questions-dashboard.html - Changed to replace x-position with xPosition.
setup.html - Changed to improve error messages.
test-questions.html - Changed to improve error messages.
test-sections.component.ts - Changed to include logic for show/hide of message, done by Asif.
test-sections.html - Changed to include hint message.
incomplete-test-creation-dialog.html - Changed to improve dialog's title and content.
test-view.component.ts - Changed to include logic for show/hide of message, done by Asif.
test-view.html - Changed to include hint message and replace x-position with xPosition.
test-create-dialog.html - Changed to improve error messages.
tests-dashboard.html - Changed to …
> After development design changes for test and questions management.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
Fixed minor binding issued
questions-single-multiple-answer.component.ts - Added missing initialisation
test.html - Added html support
**Checks**
- No known issue
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/381)
> Fixed binding issues

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#22936
TestConductController.cs - Removed JSON serialisation.
ITestConductRepository.cs - Updated AddAnswerAsync function parameter.
TestConductRepository.cs - Fixed function for adding answers. Added Transformation function. 
test.component.ts - Fixed test resuming functionality.
test-end.component.ts - Added window close function on click of the button.
conduct.service.ts - Updated addAnswer function parameter.
test-end.html - Added angular binding.
**Checks**
- No issue
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/377)
> Implementation of transformation function and fixed test resume functionality

- Trappist/src/Promact.Trappist.Core/Controllers/AccountController.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Views/Account/ForgotPassword.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
#23060, #23061
AccountController.cs - Added error message if email sending failed
IStringConstants.cs-Added FailedToSendEmailError property
StringConstants.cs-Define FailedToSendEmailError property
ForgotPassword.cshtml-Added viewbag to show the error message
setup.html-Changed error messages
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/384)
> Added error message for sendmail failed and basicsetup validations

- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
_Layout.cshtml-Added the script for embedding Chart.js library
system.config.js-Added the path for chart.js
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/385)
> Solved chart issue.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
#23070,#23071
individual-report.component.ts-Added code for printing and downloading individual test report from individual test report page.
individual-report.html-Added methods to the buttons print and download for implementing the print and download functionality of individual test report.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/386)
> Implemented print and download functionality of individual test report.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
questions-dashboard.html - Changed to include designing of appropriate message.
test-report.html - Changed to include designing of appropriate message.
test-settings.html - Changed to include designing of IP restrictions.
style.scss - Changed to include styles for IP restrictions, messages, and test logs.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/391)
> Designed IP restrictions, messages, and test logs.

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
#23178
ReportController.cs-Added method for calling the method calculating the percentile of selected attendee.
ReportRepository.cs-Added code for calculating the percentile.
IReportRepository.cs-Added interface for the method calculating the perentile of selected attendee.
reportservice.ts-Added method for calling the API calculating the percentile of selected attendee.
TestConductRepository.cs-Added code for calculating the percentage and marks scored by the attendees and store them in the database.
TestConductRepositoryTest.cs-Modified code for unit testing of Transformation()
individual-report.component.ts-Added code for calling the service respnsible for calling the API fetching the percentile of selected attendee.
**Checks**
---
This change …
> Test Assessment

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-preview/test-preview.compponent.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-preview/test-preview.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
#23238
TestConductController.cs
test-preview.html - added
test-preview.component.ts --- added
app.html
app.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/395)
> Test preview

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestAttendees.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestLogs/TestLogs.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728102437_AddedModelForTestLogs.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728102437_AddedModelForTestLogs.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728103454_AddedTestLogsInTestAttendees.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728103454_AddedTestLogsInTestAttendees.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728131810_RemovedRequiredFieldsFromTestLogs.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170728131810_RemovedRequiredFieldsFromTestLogs.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170731112402_RemovedNullValueForFinishTest.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170731112402_RemovedNullValueForFinishTest.cs
- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/testattendee.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/testlogs.model.ts
#23072,#23074,#23121,#23236,#23237
TestConductController.cs-Added Api for updating values in the test logs table.
TrappistDbContext.cs-Defined test logs model
TestAttendees.cs-Added TestLogs Model as virtual
TestLogs.cs-Added model for Test Logs.
ReportRepository.cs-Added code for including the TestLogs Details in the Attendee Details.
TestsRepository.cs-Added code for updating the Start Test field of Test Logs Model.
ITestConductRepository-Added interface for Adding Test Logs 
TestConductRepository.cs-Added code for adding values to the different fields of Test Logs.
conduct.service.ts-Added method to call API from TestConductController for adding values to the Test Logs Model.
test.component.ts-Added code for calling method from conduct.service.ts for …
> Implementation of Test Logs Feature

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Reports/ReportQuestionsCountAC.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/package-lock.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/reportquestionscount.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/testattendeerank.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/testAttendee.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
#23227
#23228
#23229
#23376
ReportController.cs - Added method to claculate allateendee marks details
ReportQuestionsCountAC.cs-Added Application class for questioncount 
IReportRepository.cs-Added method GetAllAttendeeMarksDetailsAsync()
ReportRepository.cs-Added implementation of GetAllAttendeeMarksDetailsAsync() method
ReportReporsitoryTest.cs-Added test case for repository method GetAllAttendeeMarksDetailsAsync()
report.service.ts-Added api path for the method to call controller method
reports.module.ts-Added conduct module as need in test-report component
reportquestionscount.ts-Added a ac class for holding the values from server side
test-report.component.ts-Added implementation for extra to sheet in excel and required calcualtions …
> implemented of two more excel sheet for test report

- Trappist/src/Promact.Trappist.DomainModel/DbContext/TrappistDbContext.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestCaseResult.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestCodeSolution.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170816053431_AddedTestCaseResult.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170816053431_AddedTestCaseResult.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
Fixed code snippet question page, test case filter based on test-conductor inputs and model for storing test case result
TestCaseResult.cs - Model for storing test case results
TestCodeSolution.cs - Added one to many relationship
TestConductRepository.cs - Added functionality to store test case result and filter test cases
TrappistDbContext.cs - Added TestCaseResult model
**Checks**
- If there is no default test-case provided by the test-conductor AND the test-conductor does not check to run any type of test case then code snippet question will not be executed at all. 
**Comments**
NA
--- …
> Added new model for storing test case results and fixed code snippet question page

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
#Fixed score settings for code snippet question
TestConductRepository.cs - Changed code snippet scoring
**Checks**
- NA
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/401)
> Fixed score setting for code snippet question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-preview/test-preview.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
#test preview issue
test.preview.html
test.view.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/402)
> test preview fixed

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Reports/ReportQuestionsCountAC.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/reportquestionscount.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
#23418
#23420
#23441
#23442
ReportQuestionsCountAc.cs-Added property percentile
ReportRepository.cs-Added implementation for code snippet question and percentile calculation
ReportRepositoryTest.cs-Added private method for checking code snippet question and testcase conditons
Index.cshtml-Added script for jspdf and jspdfautotable
Layout.cshtml-Removed cdn for jspdfautotable
system.config.js-Removed jspdf declaration
setup.html-Update button type fro button to submit to enable click on enter
reportquestionscount.ts-Added property percentile
test-report.component.ts-updated percentile field
profile-dashboard.component.ts-Added dialogue box property to restrict close functionality
question-dashboard.component.ts-Added dialogue box property to restrict close …
> updated test-report calculations,dialoguebox closing control and jspdf error

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/code.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
#Fixed issues with coding question on test conduct page
TestRepository.cs - Added language list in code snippet question
TestConductRepository.cs - Fixed score method
code.model.ts - Changed language datatype from number to string
test.component.ts - Fixed bug where coding solution remain unchanged even after navigating to other coding question
**Checks**
- No
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/404)
> Fixed issues with coding question on test conduct page

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#23487
TestConductController.cs - Removed checking of test status before set elapsed time
test-summary.component.ts - Added timer functionality
test.component.ts - Fixed issues with window focus and end test
test-summary.html - Modified time display
**Checks**
No known issue
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/405)
> Summary timer functionality

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
Tasks #23489
TestConductRepository.cs - Fixed Internal server error on attendee answer null
instructions.component.ts - Replace URL instead of navigation
test-summary.component.ts - Replace URL instead of navigation
test.component.ts - Fixed end test on closing window & resume test if attendee has not answer any question previously
**Checks**
- Not known
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/406)
> End test on close window fix

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
test.component.ts - Changed to include showResult variable.
test.html - Changed to include designing of code snippet.
style.scss - Changed to include design fixes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/411)
> Design fixes related to test conduct.

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Reports/CodeSnippetTestCasesCalculationAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Reports/TestCodeSolutionDetailsAC.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestCaseResult.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170819102857_Added_ForeignKeyOfCodeSnippetQuestionTestCaseInTestCaseResult.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170819102857_Added_ForeignKeyOfCodeSnippetQuestionTestCaseInTestCaseResult.cs
- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/question_status.enum.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/code-snippet-test-cases-details.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/codeSnippetTestCasesDetails.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/programminglanguage.enum.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-code-solution-details.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
#23476,#23477,#23478,#23495
ReportController.cs-Added api for fetching details of code snippet question and test code solution.
CodeSnippetTestCasesCalculationAC.cs-Added application class containing fields of code snippet test cases which are to be displayed in the individual test report page.
TestCodeSolutionDetailsAC.cs-Added application class containing fields of test code solution which are to be displayed in the individual test report page.
TestCaseResult.cs-Added a new field CodeSnippetTestCaseId 
IReportRepository,cs-Added interfaces for methods returning code snippet question test cases details, test code solution details and score obtained in code snippet questions by a test attendee.
ReportRepository.cs-Defined the methods for returning code …
> Individual report code snippet feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/testConduct.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
#23393,#23394,#23395,#23397,#23399
individual-report.component.ts-Added code for downloading individual test report on clicking the download button of test-report page and hiding percentile block till the end date for a test is over along with the number of questions attempted by the attendee being displayed.
individual-report.html-Added code for hiding the percentile block.
reports.routing.ts-Added path for individual report component on clicking the download button from the test-report page.
test-report.component.ts-Added code for navigating to the individual test report page on clicking the download button.
test-report.html-Defined the router link for download button.
testConduct.model.ts-Added questionStatus field in the client side model of …
> Solved the issues which were identified after testing

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
#traceur solution
systemjs.config.js
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/414)
> traceur changes made

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
individual-report.component.ts- Corrected the number of questions attempted by the test attendee in the individual test report page.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/415)
> Changed correct number of attempted questions by test attendee

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/CodeSnippet/Code.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/HttpUtil/HttpService.cs
- Trappist/src/Promact.Trappist.Utility/HttpUtil/IHttpService.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
Tasks #23522
Code.cs - Added Key property
TestConductRepository.cs - Added API key before post request
appsettings.json - Added CodeBaseSimulatorServerAPIKey configuration
**Checks**
- No issue
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/409)
> Now onward API key will be required to access code base server

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Startup.cs
#ip restrictions public ip
startup.cs
homecontroller.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/418)
> public ip address problem

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
#ip restrictions
homeconntroller.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/419)
> ip address restriction homecontroller modified

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Tasks #23583
questions-programming.component.ts - Fixed bug with test cases
test-summary.component.ts - Added functionality-timer will not run when in supervised mode
test.component.ts - Added warning class in timer and fixed issue with question not ending
test.html - Added ngclass and disable button functionality
questions-programming.html - Added binding to disable save button
**Checks**
-NO
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/417)
> Code snippet blank test title and other fix

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/question_status.enum.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
#23588,#23589,#23590
individual-report.component.ts-Added code for making the percentile block visible and corrected the display for scores of code snippet question.
individual-report.html-Added code for making the percentile block visible and corrected the display for scores of code snippet question.
test-summary.ts-Added code for making the line asking the candidate to confirm ending the test appear once.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/420)
> Solved issues after Testing

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/421)
> ip address changed

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
Ip restrictions 
HomeController.cs
PageNotFound.cshtml
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/422)
> Ip restrictions final change

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/423)
> ip restrictions persists

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
test-summary.component.ts-Added loader for end test button in test summary page for both supervised and unsupervised resume type of test.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/425)
> Added loader for end test button in test summary page.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
Task #23595
test-summary.component.ts - Fixed unsubscribe issue
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/424)
> Timer unsubscribe fix

- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
Task #23618
instructions.component.ts - Added fullscreen support on start test button press
test-end.component.ts - Removed useless stuffs
test-summary.component.ts - Replaced new window opening functionality with simple navigation 
test.component.ts - Fixed window closing alert and replaced window closing functionality with simple navigation
questions-programming.component.ts - Added functionality to show error to add at least one default test case before saving
questions-programming.html - Fixed html to support above fix
systemjs.config.js - Added screenfull package
package.json - Added screenfull package
**Checks**
- No Known issue
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Test conduct fullscreen fix

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
#23609
#23613
test-report.component.ts-changed loader position and getalltestattendee function calling and added loader to download excel function
instruction.component.ts-changed loader position
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/426)
> changed loader position to excel and instruction page

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/432)
> fixed lint error

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
#23614
register.html- Changed validation message from common to particular text field and maxlength of phone number and error message spelling corrected
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/430)
> Fixed registration page related issue

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
TestConductRepostory.cs-Added code for correct total marks scored calculation and handled the internal server error for review questions which are not being answered.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/431)
> Fixed the total marks scored calculation.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
individual-report.component.ts-Added code for hiding the pie chart for difficulty level pie chart when all answers given by test attendee are incorrect or not attempted.
individual-report.html-Added code for hiding the pie chart for difficulty level pie chart and display a message in place of the chart when all answers given by test attendee are incorrect or not attempted.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/434)
> Fixed the issue of empty pie chart generation on zero correct questions given by test attendee.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
#23632
#23613
#23614
instructions,html-Added loader container
registration.html- changed phone number validation and message
test.html-changed button name and show note for multiple answer question
add-category-dialogue.component.ts-Changed snackbar message
individual-report.component.ts-changed pdf file name and title
test-report.component.ts-changed excel and pdf file name
**Checks**
N/A
**Comments**
N/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/435)
> fixed bug related to category and updated modules as per requirement

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/CodeSnippet/Code.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/code.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
Tasks #23626
TestConductRepository.cs - Fixed 400 error and added functionality to store code result
Code.cs - Added result field
code.model.ts - Added result field
test-summary.component.ts - Unsubscribed timer
create-test-header.component.ts - Added fullscreen support for preview question
test-view.component.ts - Added fullscreen support for preview question
test.component.ts - Fixed code solution displaying issue
test.html - Fixed binding issue
**Checks**
- Snackbar for window focus lost will show on test-summary and test-end page.
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/436)
> Test coding question fix

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/PageNotFound.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
HomeController.cs - Changed to remove ip address displayed on 404 page.
PageNotFound.cshtml - Changed to remove ip address displayed on 404 page.
instructions.html - Changed to include some more instructions.
test-report.html - Changed to fix table footer design.
style.scss - Changed to include design changes for test conduct module and reports.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/438)
> Design changes related test conduct and reports.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
test-settings.html-Added the event for firing of validation messages for start and end date.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/437)
> Added an event for firing of validation messages for start and end test date.

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
ReportController.cs-Added method for fetching total number of attempted questions by test attendee.
IReportRepository.cs-Added interface for method fetching total number of attempted questions by test attendee.
ReportRepository.cs-Added method for fetching total number of attempted questions by test attendee.
report-service.ts-Added service for calling api for the method fetching the total number of questions attempted by test attendee.
individual-report.component.ts-Added code for displaying the total number of attempted questions by test attendee.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/439)
> Fixed the calculation for total number of attempted questions being displayed in the individual test report page.

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
#23609
ReportRepositoryTest.cs
test-report.component.ts
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/440)
> changed calculation for review type question

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#snakcbar
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/442)
> Bug browser tollerance

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
23609
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/445)
> Update testreport excel calculation

- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
#TestEnd
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/444)
> Test End Problem

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
test.component.ts-Added code for preventing opening of instruction page on clicking browser back button from test-end page.
test-end.component.ts-Added code for preventing opening of instruction page on clicking browser back button from test-end page.
ReportController.cs-Added code for handling null reference exception.
TestConductController.cs-Added code for handling null reference exception.
ReportRepository.cs-Added code for handling null reference exception.
TestConductRepository.cs-Added code for handling null reference exception.
ITestConductRepository.cs-Added return type to an existing method for handling null reference exception.
**Checks**
--- …
> Fixed issue browser back button

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/447)
> modified end test

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/gulpfile.js
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
Answered question can be editable, full-screen for production is fixed and wrong code display is fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/443)
> Fixes - Editable answer, fullscreen, wrong code message

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
#23609
test-summary.html
test-summary.component.ts
instructions.html
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/448)
> changed db queries for excel calculation

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
conduct.service.ts-changed the routing for calling getSummary()
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/450)
> Fixed the test-summary issue.

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
23609
**Checks**
N/a
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/453)
> changed db queries

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
instructions.component.ts-Added code for disabling browser back button.
test-end.component.ts-Added code for disabling browser back button.
test.component.ts-Added code for disabling browser back button.
test-summary.component.ts-Added code for disabling browser back button.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/454)
> Browser back button issue fixed

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.model.ts
#Resume Test feature
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/452)
> Resume Test

- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/tests-programming-guide-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/tests.programming-guide.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
Added programming guide dialog box and fixed issues with test conduct page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/456)
> Added programming guide dialog box

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/459)
> Feature update: Any question can be marked

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/461)
> url block end solved

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestAttendees.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170828120009_AddedAttendeeBrowserToleranceCountFieldInTestAttendees.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170828120009_AddedAttendeeBrowserToleranceCountFieldInTestAttendees.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test_attendee.model.ts
test.component.ts-Added code for fetching and updating the correct browser tolerance value of an attendee.
TestConductController.cs-Added code for returning the correct browser tolerance count of an attendee.
ITestConductRepository.cs-Added interface for the method returning the correct browser tolerance value of an attendee.
TestConductRepository.cs-Added code for returning the correct browser tolerance value of an attendee.
conduct.service.ts-Added service for calling the method returning the correct browser tolerance value of test attendee.
testAttendee.model.ts-Added attendeeBrowserToleranceCount field in the test attendee model.
TestAttendees.cs-Added attendeeBrowserToleranceCount field in the test attendee model.
**Checks**
---
This change is [<img …
> Changed the calculation for browser tolerance for an attendee.

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/http.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/463)
> Error message when attendee re-register after completing test

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#Test 
test-summary.component.ts- added subscribe for subject
conductServices.ts - Added BehaviorSubject
TestConductRepository.cs- removed status line
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/464)
> Solved test status for expired test, and countdown time issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/466)
> Implemented unmark for review button

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-end/test-end.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#Test summary
test-summary.component.ts- get status for test block and expired
test-summary.html- added message for block and expired test
test.component.ts-saved status for test block and test expired
test.html-
test-end.component.ts- removed unused codes
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/467)
> Test summary feature

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/468)
> Fixed bug with question status changing for reviewed question

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/469)
> Time sync fix

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/470)
> Question index colour changes back to black on unmarking

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Reports/ReportQuestionsCountAC.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/reportquestionscount.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
23609
ReportQuestioncountAc.cs-added totaltestquestion property
ReportRepository.cs-added count for total test questions
testreportquestioncount.ts- added property totalTestQuestions
test-report.component.ts-Changed calling of methods position and removed insturction api call
test-report.html-Changed function name on downloadexcel button click
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/458)
> Removed unneccesary api call and count totaltestquestions directly

- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/Views/_ViewImports.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/http.wrapper.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/473)
> Miniprofiler

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
23717-changed download excel functionality by splitting it into two ways
test-repot.html-added button for basic excel download
test-report.component.ts-added code for downloading excel withbasic information 
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/474)
> Generate basic excel sheet 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#ctrl+s,ctrl+p,ctrl+u,ctrl+o commands are restricted
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/475)
> Restricted keyboard events

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
#fixed issues for relaunch ,launch,pause and resume
test-settings.component.ts
test-settings.html
create-test-footer.html
create-test-footer.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/479)
> Test settings pause resume relaunched handled

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
#23638
individual-report.component.ts-Added code for hiding the percentile,percentage and score blocks until the values are fetched and are ready to be displayed.
individual-report.html-Added conditions for hiding the percentile,percentage and score blocks until the values are fetched and are ready to be displayed.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/480)
> Fixed bug #23638.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
#21966
register.html-Added asterisk sign for required fields.
change-password-dialog.html-Added asterisk sign for required fields.
profile-edit.html-Added asterisk sign for required fields.
add-category-dialog.html-Added asterisk sign for required fields.
questions-programming.html-Added asterisk sign for required fields.
setup.html-Added asterisk sign for required fields.
test-settings.html-Added asterisk sign for required fields.
test-create-dialog.html-Added asterisk sign for required fields.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/481)
> Added asterisk for all the required fields.

- Trappist/src/Promact.Trappist.DomainModel/Enum/TestStatus.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/enum-test-state.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
Task #23727
TestStatus.cs - Added UnfinishedTest property
ReportRepository.cs - Added test status from completed to unfinished
test-report.component.ts - Fixed issue with test status type and attendee selection
**Checks**
- Design issue on report page when generating report of multiple attendee one by one.
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/482)
> Added unfinished test status

- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test_attendee.model.ts
Task #23747
Conduct.cshtml - Added alea.js for pseudo random number generation
test.component.ts - Added random number generation using seed
test_attendee.model.ts - Type change of rollnumber from number to string
**Checks**
- No issue
**Comments**
Attendee's email id and roll number is used as a seed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/483)
> Added random generation with seed

- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
Fixed alea PRNG cdn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/485)
> Fixed alea CDN call

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
#23738
TestsRepository.cs-Added code for duplicating a test along with its Ip Address.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/486)
> Fixed bug #23738

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/single-multiple-answer-question-option.model.ts
#Tried to modify methods as much as possible,trim undefined errors resolved
questions-single-multiple-answer.component.ts
single-multiple-answer-question-option.model.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/488)
> console errors solved..method GetAllTestAsync() method modified.

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#23708,#23709 (Bugs related to duplicate test already launched and remove option for edit question or duplicate question)
questions-single-multiple-answer.component.ts
create-test-footer.component.ts
test-settings.html
test-dashboard.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/484)
> Duplicate test(bug)

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-preview/test-preview.compponent.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#ctrl+h,ctrl+d,ctrl+j,ctrl+f,ctrl+g,ctrl+r   disabled
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/478)
> ctrl+h,ctrl+d,ctrl+j,ctrl+f,ctrl+g,ctrl+r   disabled

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
#23718 - Fixed the score calculation bug.
TestConductRepository.cs- Added condition for proper calculation of score when an attendee has marked a question for review and left it unanswered.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/495)
> Fixed the score calculation bug.

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Test/TestAC.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/Test/Test.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170906081354_Added-Focus-Lost-Field-TestModel.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170906081354_Added-Focus-Lost-Field-TestModel.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
#23746(bug) test with same name generated solved.
TestAC.cs
Test.cs
TestsRepository.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/494)
> Focuslost time added,23746 bug solved

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/add-category-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
#23717
add-category-dialog.component.ts
question-dashboard.component.ts
question-dashboard.html
questions-programming.component.ts
questions-programming.html
question-single-multiple-answer.component.ts
question-single-multiple.answer.html
question.routing.ts
questions.service.ts
test-dashboard.component.ts
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/489)
> Implemented preselection categorydifficulty

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
#23717
test-report.html
test-report.component.ts
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/492)
> implmentation of Count attendees bytesttype ,no record found handling and starred candidate filtering 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-IPAdddress.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
create-test-footer.component.ts-Included variables using @Input to disable the buttons present in the footer of test settings page when ip address fields are null.
create-test-footer.html-Added conditions to disable the buttons present in the footer of test settings page according to the ip restriction field values.
create-test-header.component.ts-Changed the pattern of test name in header.
test-sections.component.ts-Removed the console line.
test-settings.component.ts-Added code for proper adding of ip restriction fields.
test-settings.html-Added conditions for firing validation messages for ip restriction fields.
test-IPAddress.ts-Added a boolean variable.
**Checks**
--- …
> Ip restriction issue fixed

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
#23718-Fixed issue of unfinished test status in individual test report page.
individual-report.component.ts-Added test status for tests that are unfinished in individual test report page.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/496)
> Added test status for unfinished test.

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
Tasks #23843
Added AsNoTracking() method where ever possible for test conduct to load faster.
Optimised some db calls inside loops.
**Checks**
- NA
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/497)
> Optimised db calls for test conduct page

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
Added colour code for result and restricted navigation on coding question 
test.component.ts - Added colour code for code result and restricted navigation
**Checks**
- For now colour code for code result is decided by searching result string for keywords
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/500)
> Added colour code for result and restricted navigation on coding question 

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
#23718
ReportController.cs - Added testId in the api of percentile calculation method.
IReportRepository.cs-Added testId as parameter in the percentile calculation method.
ReportRepository.cs-Added testId as parameter in the percentile calculation method and optimised the code accordingly and condition added by Asif in SetTestStatusAsync().
ReportsRepository.Test.cs-Added unit testing for CalculatePercentileAsync().
report.service.ts-Added testId in the service calling the percentile calculation method.
individual-report.component.ts-Passed the testId in the method calling the service for percentile calculation method.
test-settings.html-Added condition for hiding the close icon of ip restriction fields in test settings page - Asif.
**Checks**
---
This …
> Percentile unit testing.

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
#23718
ReportRepository.cs-Optimized the method getTestAttendeeAnswers().
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/502)
> Optimized getTestAttendeeAnswers().

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
#23717
1. test-report.component.ts- Added code for count starred candidate initially and instantly also 
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/503)
> changedcount calculation for starred candidate

- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#23892
1. IReportRepository.cs-changed task type
2. ReportRepository.cs-optimised method gettestnameasync
3. question-programming.component.ts-added loader for editing and duplicate method
4. question-programming.html-added loader condition
5. question-single-multiple-component.ts-added loader for editing and duplicate method
6. question-single-multiple.html-added loader div tag
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/505)
> Improper loader issue

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
Page not found fix
TestRepository.cs - Fixed initialising attendee start date when attendee start date already exist. Added AsNoTracking in Db calls in GetTestById method.
**Checks**
- No
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/498)
> Fixed page not found bug

- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
#Focus Lost Time Null Value Exception
test-settings.component.ts
test-settings.html
craete-test-footer.componrnt.ts
create-test-footer.html
**Checks**
- issue 1
- issue 2
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/506)
> Focus Lost time null problem solved

- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
#23698
_Layout.cshtml-Added chart.js script above other scripts in layout.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/491)
> Solved bug #23698.

- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
StringConstants.cs - Changed to include minor changes in code assessment messages on test conduct.
test.component.ts - Changed to include class names for code assessment messages block on test conduct.
test.html - Changed to include cursor related class.
test-report.html - Changed to include proper structure for action items.
style.scss - Changed to include design changes for test conduct and report.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/507)
> Design improvements for test conduct and report.

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
#Test-Question-Addition modified
test-question.component.ts
test-settings.html
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/508)
> Test-Question-Selection modified

- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
#solved test settings duplicate problem
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/510)
> fixed test- settings duplicate problem

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#23717
1. test-reports.component.ts- added confirmation alert before generating reports for unfinished test
2. test-report.html- changed button class by shreel bhatt
3. style.css- modified property by shreel bhatt
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/511)
> confimation message added for unfinish report

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
#solved test link access problem when start date has not come 
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/512)
> solved link access while start date has not come yet

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/513)
> Merged Dev into Staging

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/instructions/instructions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
instructions.html - Changed to include E2E classes.
register.html - Changed to include E2E classes.
test.html - Changed to include E2E classes.
test-summary.html - Changed to include E2E classes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/520)
> E2E classes added.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
test.html - Changed to include E2E classes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/522)
> Added E2E classes on test conduct.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
test.html - Changed to include E2E class for timer.
test-summary.html - Changed to include E2E classes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/523)
> Added E2E classes for test summary.

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
#Added proper comments for all the methods written.
ReportController,cs-Corrected spelling mistakes and modified the comments for methods.
TestConductController.cs-Modified comments for GetTestSummaryAsync().
TestController.cs-Modified comments for DuplicateTest()
IReportRepository.cs-Modified comments for GetAttemptedQuestionsByAttendeeAsync()
TestsRepository.cs-Removed the comments for UpdateTestNameAsync()
ITestConductRepository.cs-Modified comments for GetTestSummaryDetailsAsync()
ITestsRepository.cs-Modified comments for DuplicateTest()
individual-report.component.ts-Added comments for convertTestLogsDateTimetoLocalDateTime() and modified comments for correctPieChart()
test-report.component.ts-Removed unused navigateToIndividualReportPage() …
> Added proper comments for the methods written.

- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
#23937,#23938,#23939
ReportsRepositoryTest.cs-Added unit testing for methods which were missing unit testing and added proper comments for the methods.
TestsRepositoryTest.cs-Added proper comments for all the unit testing methods.
TestConductRepositoryTest.cs-Added unit testing for methods which were missing unit testing and added proper comments for the methods.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/517)
> Unit Testing

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
#23996
TestConductRepository.cs-Added comments and changed variable names to make GetTotalMarks() readable.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/519)
> Made the method calculating the total marks scored by a test attendee more readable.

- Trappist/src/Promact.Trappist.DomainModel/Models/Report/Report.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170913090016_AddedPRopertyToReportModel.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170913090016_AddedPRopertyToReportModel.cs
- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/reportquestionscount.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
#23940
1. Report.cs-Added property TotalCorrectAttempts to report model
2. ReportRepository.cs-Modified Calculations for excel generation
3. TestConductRepository.cs-Added calculation for correct attempts
4. ReportRepositoryTest.cs-Modified unit testing
5. report-model.ts-Added totalCorrectAttempts field
6. report.ts-Added property totalCorrectAttempts
7. test-report.component.ts-Modified download-excel method
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/521)
> Optimize excel generation

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
#24029
ReportReposiory.cs-GetCodeSnippetDetailsAsync() and GetTestCodeSolutionDetailsAsyn() methods changed.
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/524)
> code display problem solved

- Trappist/src/Promact.Trappist.Core/Controllers/TestController.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Question/QuestionAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Test/TestCategoryAC.cs
- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/Test/TestQuestionAC.cs
- Trappist/src/Promact.Trappist.Repository/Test/ITestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Test/Questions/QuestionsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/Tests/TestsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.service.ts
#optimized test module and corresponding unit testing methods
TestController.cs
TestQuestionAC.cs
ITestsRepository.cs
QuestionsRepositoryTest.cs
TestRepositoryTest.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/526)
> Edit select question

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
- Trappist/src/Promact.Trappist.Repository/Reports/IReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/report.service.ts
#24015
ReportController.cs- Added code for getting the list of attendee Ids from the report table.
IReportRepository.cs- Added interface for the method getting the list of attendee Ids from the report table.
ReportRepository.cs - Added code for defining the method getting the list of attendee Ids from the report table.
ReportsRepositoryTest.cs-Added unit testing for the method getting the list of attendee Ids from the report table.
individual-report.component.ts-Added code for navigating from one candidates' report to another.
individual-report.html-Added buttons for navigating from one candidates' report to another.
report.service.ts-Added code for calling the method getting the list of attendee Ids from the report table.
**Checks**
---
This change …
> Individual report navigation functionality.

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
**Fixed Issues*
Individual test case fix
ReportRepository.cs - Added OrderByDescending on db call
**Checks**
- 
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/514)
> Fixed Test case display issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
#fixed issue create test, while creating test in select section and select question part it was showing you cannot edit ongoing test.
test-section.component.ts
test-question.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/529)
> fixed create test issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
#bug related to navigation from one candidate's report to another.
individual-report.component.ts-changed code for navigation from one candidates' report to another.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/531)
> Solved the bug of navigation from one candidate's report to another.

- Trappist/src/Promact.Trappist.DomainModel/ApplicationClasses/TestConduct/TestAnswerAC.cs
- Trappist/src/Promact.Trappist.DomainModel/Models/TestConduct/TestConduct.cs
- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170925064206_IsAnsweredAddedTestConductTable.Designer.cs
- Trappist/src/Promact.Trappist.Web/Migrations/20170925064206_IsAnsweredAddedTestConductTable.cs
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/appsettings.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test_answer.model.ts
#Mark for review problem, in test conduct if any coding  question is marked for review and then navigate to next question then this questions is getting saved as unanswered instead of review
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/530)
> mark for review problem checks

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
TestConductRepository.cs -
test.component.ts -
ReportRepository.cs -
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/532)
> score calculation on the basis of latest answer added

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
Clear response color changing problem
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/533)
> changing color problenm for unattempt questions

- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#prevented alert dialogue from test summary page
test-summary.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/535)
> prevented propagation of alert dialogue

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/testAttendee.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
#Fixed issue generatedetailreport problem , disabled save and run code is compiling and disabled redirect to individual report
test.html
test-report.component.ts
test-report.html
testAttendees.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/536)
> Attempted quesion problem

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/category.model.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-launch-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
#24086
category.model.ts-Added a number type variable for storing the number of questions to be randomly selected.
test-questions.component.ts-Added code for selecting random questions from a particular category.
test-questions.html-Added button for calling methods shuffling the question array of a category and opening the dialog where the number of questions to be selected randomly is to be entered.
test-view.component .ts-Removed unnecessary declarations.
test-settings.component.ts-Removed unnecessary declarations.
test-sections.component.ts-Removed unnecessary declarations.
tests.module.ts-Changed the name of the TestLaunchDialogComponent.
test-launch-dialog.component.ts-Added code for entering number of questions that is to be selected randomly and …
> Random question selection functionality

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions.routing.ts
#21870
question-dashboard.component.ts-Added implementation for search text will stay even after category select
question-dashboard.html
question.routing.ts-Added route for search 
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/540)
> Implemented search text consistency on switching of category or difficulty 

- Trappist/src/Promact.Trappist.Core/Controllers/HomeController.cs
- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Utility/Constants/IStringConstants.cs
- Trappist/src/Promact.Trappist.Utility/Constants/StringConstants.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
#No two register page will be opened in same browser
HomeController.cs
register.component.ts
TestConductController.cs
StringConstants.cs
IStringConstants.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/542)
> no two register page will open for tha same test in the same browser

- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
#24107
app.html
test-view.html
test-dashboard.html
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/541)
> changed routing tags for all modules and removed download detailed excel button 

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#24139
questions-programming.html-added disable property
questions-single-multiple-answer.html-added disable property
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/544)
> fixed bug-adding on multiple click of save button

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#24136
questions-dasboard.component.ts
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/546)
> Resolved bug wrong question count

- Trappist/src/Promact.Trappist.Core/Controllers/ReportController.cs
#24165
ReportController.cs - only one line added in CreateSessionForAttendee 
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/548)
> Fixed bug On Test Link Wrong Screen Coming

- .travis.yml
- Dockerfile
- Trappist/src/Promact.Trappist.Core/Promact.Trappist.Core.csproj
- Trappist/src/Promact.Trappist.DomainModel/Models/ApplicationUser.cs
- Trappist/src/Promact.Trappist.DomainModel/Promact.Trappist.DomainModel.csproj
- Trappist/src/Promact.Trappist.Repository/BasicSetup/BasicSetupRepository.cs
- Trappist/src/Promact.Trappist.Repository/Promact.Trappist.Repository.csproj
- Trappist/src/Promact.Trappist.Repository/Questions/QuestionRepository.cs
- Trappist/src/Promact.Trappist.Repository/Test/TestsRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/Bootstrap.cs
- Trappist/src/Promact.Trappist.Test/Promact.Trappist.Test.csproj
- Trappist/src/Promact.Trappist.Test/Reports/ReportsRepositoryTest.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Utility/Promact.Trappist.Utility.csproj
- Trappist/src/Promact.Trappist.Web/Program.cs
- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Shared/_Layout.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
#methods modified and unit testing methods changed
Startup.cs 
Promact.Trappist.Web.csproj
Promact.Trappist.Test.csproj
Promact.Trappist.DomainModel.csproj
QuestionRepository.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/537)
> .net core 1.1 to 2.0 converted

- .circleci/config.yml
- .travis.yml
- README.md
- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/553)
> integrated circleci

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
#24233
ReportRepository.cs-Modified GetTestQuestions().
TestConductRepository.cs-Modified GetTotalMarks().
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/555)
> Modified methods GetTotalMarks and GetTestQuestions for resolving the breaking changes due to updated visual studio.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared-components.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared.module.ts
#24106
shared.module.ts-Removed unnecessary declarations.
conduct.module.ts-Removed unnecessary material and declarations.
shared-components.module.ts-Added the modules shared by all the modules.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/549)
> Removed unnecessary angular material from conduct module.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/duplicate-test-dialog.component.spec.ts
test-view.component.spec.ts-Removed unnecessary import lines.
delete-test-dialog.component.spec.ts-Removed unnecessary import lines.
duplicate-test-dialog.component.spec.ts-Removed unnecessary import.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/560)
> Removed unnecessary import lines.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
#24318
question-dashboard.component.ts-changed on scrolling function call
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/556)
> resolved bug of wrong questions showing on dashboard

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#24139
question-single-multiple-answer.component.ts-Added method to stop click
question-single-multiple-answer.html- Added condition
question-programming.component.ts-Added method to stop click
question-programming.html-Added condition
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/557)
> Resolved bug related to save button problem in question module

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.spec.ts
#24323
ReportRepository.cs - Added correct marks in test object
test-report.component.ts-Added outofmarks field in excel
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/565)
> Added outofmarks field in excel sheet

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
#24139
question-programming.html-Added button disabled on form submit
single-multiple-answer.html-Added button disabled on form submit
**Checks**
N/A
**Comments**
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/564)
> resolved bug 24139

- Trappist/src/Promact.Trappist.Repository/Reports/ReportRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
#24388
ReportRepository.cs-Modified GetTestQuestions().
TestConductRepository.cs-Modified GetTotalMarks().
individual-report.component.ts- Modified code for displaying the correct and  incorrect options in individual test report page.
individual-report-component.spec.ts - Modified the unit testing method accordingly.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/561)
> Optimized GetTotalMarks() and GetTestQuestions().

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
#24540
test.component.ts-Added code for solving the improper log time issue of closing window without finishing test.
individual-report.html-Solved minor display issue of test logs time.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/566)
> Fixed issue related to improper close window without finishing test log time.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-question.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-section.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/delete-test-dialog.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-dashboard.component.spec.ts
#24194
create-test-footer.component.ts - Added code for getting url value using service.
create-test-footer.component.spec.ts - Added specs for increasing branch coverage of create-test-footer component.
test-question.spec.ts - Added MockRouteService in the provider.
test-section.component.spec.ts - Added MockRouteService in the provider.
test-settings.component.spec.ts - Added MockRouteService in the provider.
test-view.component.spec.ts - Added MockRouteService in the provider.
test-dashboard.component.spec.ts - Added MockRouteService in the provider.
delete-test-dialog.component.ts - Added code for getting url value using service.
delete-test-dialog.component.spec.ts - Added and modified specs for increasing branch coverage of delete-test-dialog …
> Increased branch coverage of delete-test-dialog and create-test-footer components.

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
- Trappist/src/Promact.Trappist.Core/Promact.Trappist.Core.csproj
- Trappist/src/Promact.Trappist.Core/TrappistHub/TrappistHub.cs
- Trappist/src/Promact.Trappist.Repository/Promact.Trappist.Repository.csproj
- Trappist/src/Promact.Trappist.Repository/TestConduct/ITestConductRepository.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/Startup.cs
- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/karma.conf.js
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/conduct.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/tests-summary.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/connection.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/shared/shared-components.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests.module.ts
#Real time test report and test-summary
TrappistHub.cs - Added 
TestConductController.cs
Startup.cs
Index.cshtml
Conduct.cshtml
connection.service.ts - Added 
test-summary.component.ts
test-report.component.ts
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/552)
> Signal r real time

- Trappist/src/Promact.Trappist.Core/Controllers/TestConductController.cs
#24280 bug for new test link 
TestConductController.cs- modified
**Checks**
- issue 1
- issue 2
**Comments**
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/559)
> Fixed bug i.e after blocked or expired test no new test starting

- Trappist/src/Promact.Trappist.Web/gulpfile.js
gulpfile.js - signalr script added
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/574)
> signalr added to bundle

- Trappist/src/Promact.Trappist.Web/Views/Account/Login.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/test-create-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
Login.cshtml - Changed to include e2e classes.
create-test-footer.html - Changed to include e2e classes.
test-sections.html - Changed to include e2e classes.
test-create-dialog.html - Changed to include e2e classes.
tests-dashboard.html - Changed to include e2e classes.
app.html - Changed to include e2e classes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/576)
> Added some e2e classes.

- Trappist/src/Promact.Trappist.Web/package.json
Added gulp sass command before ng build
package.js
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/577)
> Added sass build before production build

- Trappist/src/Promact.Trappist.Web/Views/Home/Conduct.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/Views/Home/Setup.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/app.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/change-password-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-dashboard/profile-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/profile/profile-edit/profile-edit.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-single-multiple-answer/questions-single-multiple-answer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/setup/setup.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-footer/create-test-footer.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-questions/test-questions.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-sections/test-sections.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-settings/test-settings.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/test-view/test-view.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/duplicate-test-dialog.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/tests-dashboard/tests-dashboard.html
18 html & 3 cshtml files changed to include E2E Classes.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/584)
> Added E2E Classes.

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.html
- Trappist/src/Promact.Trappist.Web/wwwroot/css/style.scss
test.html - Changed to include styling for custom input.
style.scss - Changed to include styles for custom input.
**Checks**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/585)
> Design changes for custom input.

- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/question-dashboard.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/tests/shared/create-test-header/create-test-header.component.ts
Tasks #25363
Index.cshtml
questions-dashboard.component.ts
questions-programming.component.ts
questions-programming.html
create-test-header.component.ts
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/586)
> Bug fixes and fixed screenfull.js issue in test preview

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
Removed null check with CodeResponse instead using empty string to validate
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/587)
> Fixed code response empty issue

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/tests.programming-guide.html
Tasks #25130
test.component.ts - Fixed formatting issue and closed the dialog box (if not already) on test expiry.
tests.programming-guide.html - Added some common mistakes
**Checks**
**Comments**
***Do you have any suggestion? Want to add some common mistakes? Drop a comment here before it merges*** :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/582)
> Added some common programming mistakes made by beginners

- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
Changed and arranged some column in excel sheet
test-report.component.ts - changes to excel sheet...(And I have also put a small signalr bug fix :) ) 
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/581)
> Excel sheet changes

- Trappist/src/Promact.Trappist.Web/Promact.Trappist.Web.csproj
- Trappist/src/Promact.Trappist.Web/karma-test-shim.js
- Trappist/src/Promact.Trappist.Web/karma.conf.js
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/Mock_Data/conduct_data.mock.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
Tasks #24358
karma.conf.js - Added dependencies
conduct_data.mock.ts - Mock data for testing
test.component.spec.ts - Added unit tests for test conduct page
**Checks**
nothing
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/568)
> Client side ut test conduct

- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
Fixed bug where the programming question is saved without any test case
questions-programming.component.ts
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/588)
> Programming question requires atleast a single default test case

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
- Trappist/src/Promact.Trappist.Repository/Categories/ICategoryRepository.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
Tasks #25836
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/590)
> Bug fix category

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/connection.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.spec.ts
Task #26089
test-summary.component.ts - Fixed realtime update
connection.service.ts - Handled connection issue
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/591)
> Bug fix - Report update realtime

- Trappist/src/Promact.Trappist.Web/Views/Home/Index.cshtml
- Trappist/src/Promact.Trappist.Web/package.json
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/question-dashboard.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/reports.module.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/test-report/test-report.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/systemjs.config.js
Fixed issue in question dashboard page.
Fixed time issue in pdf and excel sheet
Feature #25127
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/592)
> Bug fix list:

- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
Time taken fix
TestConductRepository.cs - Fixed time taken by attendee
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/594)
> Time taken fix

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Core/TrappistHub/TrappistHub.cs
- Trappist/src/Promact.Trappist.Repository/TestConduct/TestConductRepository.cs
- Trappist/src/Promact.Trappist.Test/TestConduct/TestConductRepositoryTest.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/register/register.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/connection.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-dashboard/questions-dashboard.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/questions/questions-programming/questions-programming.html
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.spec.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.ts
- appveyor.yml
Tasks #26482
**Checks**
Time Logs shown in report page may not be accurate.
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/595)
> Time and other bug fixes

- Trappist/src/Promact.Trappist.Core/TrappistHub/TrappistHub.cs
- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test/test.component.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/core/connection.service.ts
- Trappist/src/Promact.Trappist.Web/wwwroot/app/reports/individual-report/individual-report.component.spec.ts
Tasks #26482:
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/598)
> Time taken issue on resume and some real-time issue fixed

- Trappist/src/Promact.Trappist.Web/wwwroot/app/conduct/test-summary/test-summary.component.ts
Time taken by attendee in unsupervised test.
**Checks**
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/600)
> Accurate time taken for unsupervised test

- Trappist/src/Promact.Trappist.Core/Controllers/QuestionController.cs
- Trappist/src/Promact.Trappist.Repository/Categories/CategoryRepository.cs
**Checks**
- issue 1
- issue 2
**Comments**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/promact/trappist/601)
> Fixed IsCategoryExistAsync method
